export enum ErrorCode {
    NO_USER = 'NO_USER',
    NO_DEPOSIT = 'NO_DEPOSIT',
    EMAIL_EXISTS = 'EMAIL_EXISTS',
    USER_EXISTS = 'USER_EXISTS',
    DEPOSIT_SAVE_ERROR = 'DEPOSIT_SAVE_ERROR',
    USER_SAVE_ERROR = 'USER_SAVE_ERROR',
    AUTHENTICATION_FAILED = 'AUTHENTICATION_FAILED',
    REGISTRATION_FAILED = 'REGISTRATION_FAILED',
}